## Universal Function: Fast Element-wise Array Function

A universal function, or ***ufunc***, is a function that performs elementwise operations on data in ndarrays. You can think of them as fast vectorized warppers for simple functions that takes one or more scalar values and produce one or more scalar results.
> Many ufuncs are simple elementwise transformations, like *sqrt* or *exp*:

In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Squre Root of element or array
print(np.sqrt(arr))

print("The Square Root of {0}?? is", np.sqrt(16))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
The Square Root of {0}?? is 4.0


These are referred to as unary ufuncs. Others, such as add or maximum, take 2 arrays (thus, binary unfuncs) and return a single array as the result:

In [36]:
# Created 2 arrays of 3 random numbers

x = np.random.randn(3)

y = np.random.randn(3)

x ,y

(array([0.80673006, 1.6581791 , 0.20639097]),
 array([-0.37385098, -0.41708117, -0.16638126]))

In [37]:
# Finding the maximum number element wise in x and y array

np.maximum(x, y)

array([0.80673006, 1.6581791 , 0.20639097])

*modf* function return the fractional and integral parts of a floting point array:

In [49]:
arr = np.random.randn(7)*14

arr

array([-25.66103978,  23.46936992,  -5.48780522,   4.45242312,
        -5.48410178,   5.55781883,  -5.00657325])

In [50]:
np.modf(arr)

(array([-0.66103978,  0.46936992, -0.48780522,  0.45242312, -0.48410178,
         0.55781883, -0.00657325]),
 array([-25.,  23.,  -5.,   4.,  -5.,   5.,  -5.]))

![Unary ufuncs](../../Pictures/unary%20ufuncs.png)

![Binary Unversal Function](../../Pictures/Binary%20universal%20fuctions.png)