## Linear Algebra

Linear algebra, like matrix multiplication, decompositions, determinants, and other square matrix math, is an important part of any array library. Unlike some languages like MATLAB, multiplying two two-dimensional arrays with * is an element-wise product instead of a matrix dot product. As such, there is a function dot, both an array method, and a function in the numpy namespace, for matrix multiplication:

In [2]:
import numpy as np

In [4]:
x = np.array([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.,]])

y = np.array([[6., 23.], [-1, 7], [8, 9]])

x, y

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 array([[ 6., 23.],
        [-1.,  7.],
        [ 8.,  9.]]))

In [5]:
x.dot(y)  # equivalently np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.],
       [106., 298.]])

A matrix product between a 2D array and a suitably sized 1D array results in a 1D array:


In [17]:
np.dot(x, np.ones(3))

array([ 6., 15., 24.])

numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant. These are implemented under the hood using the same industry-standard Fortran libraries used in other languages like MATLAB and R, such as like BLAS, LAPACK, or possibly (depending on your NumPy build) the Intel MKL:

In [18]:
from numpy.linalg import inv, qr

In [19]:
X = np.random.randn(5,5)

In [20]:
mat = X.T.dot(X)

In [21]:
inv(mat)

array([[ 6.09926253, -0.7163031 ,  1.61479132, -2.69540099, -1.40801136],
       [-0.7163031 ,  0.18112967, -0.28356888,  0.35876804,  0.26173436],
       [ 1.61479132, -0.28356888,  0.87261284, -0.97255188, -0.81514325],
       [-2.69540099,  0.35876804, -0.97255188,  3.39569482,  1.57091028],
       [-1.40801136,  0.26173436, -0.81514325,  1.57091028,  1.27345065]])

In [22]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  1.13814870e-16,  5.09646906e-16,
         2.60532585e-17,  2.86037786e-16],
       [ 6.86010936e-16,  1.00000000e+00,  3.29257675e-16,
         2.73062608e-16, -1.58947273e-16],
       [-3.99460705e-15,  2.50361977e-16,  1.00000000e+00,
         1.22913586e-15,  1.63221576e-16],
       [ 1.21326049e-16,  1.79637018e-16, -5.79140414e-17,
         1.00000000e+00,  8.03218731e-16],
       [-1.27481505e-15, -1.89792351e-16, -2.41336652e-16,
        -7.17315185e-16,  1.00000000e+00]])

In [23]:
q, r = qr(mat)

In [25]:
r

array([[ -1.35493354,  -7.45615251,   2.57805136,  -1.22920516,
          3.48526236],
       [  0.        , -10.98432414,  -5.76853996,   0.67753786,
         -2.43939516],
       [  0.        ,   0.        ,  -1.5654715 ,   0.06604016,
         -1.41065597],
       [  0.        ,   0.        ,   0.        ,  -0.94562343,
          1.66985845],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.38334454]])

![Commonly used numpy.linalg function](../../Pictures/Commonly%20used%20numpy.linalg%20function.png)