# A Python List Is More Then Just a List

The standard mutable mulitelement container in python (list).

In [1]:
L = list(range(10))

L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(Out[1])

list

In [3]:
L2 = [str(c) for c in L]

In [4]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
L3 = [bool, '2', 3.1, 4]
[type(item) for item in L3]

[type, str, float, int]

In [6]:
del L3

## Creating Arrays from python Lists

we can use np.array to create arrays from Python lists:

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

If we want to make array of a type (e.g. float, str), we can use dtype keyword:

In [9]:
np.array([1,2,3,4,5,6], dtype= str)

array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

In [10]:
# or 
np.array([1,2,3,4,5,6], dtype=float)

array([1., 2., 3., 4., 5., 6.])

### *Unlike python Lists, numpy arrays can be multidimensional.*

In [11]:
# nested list result in multidimensional arrays

np.array([range(i + 1, i + (4)) for i in [1,2,3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [12]:
np.array([range(p , p + 3 ) for p in [2,1,3]])

array([[2, 3, 4],
       [1, 2, 3],
       [3, 4, 5]])

## Creating Arrays From Scratch

In [13]:
np.random.normal(2, 20, (3,3))

array([[-13.87344071, -26.69895952,   1.58924385],
       [-17.69010991,  21.40362035,  -2.44213357],
       [  4.82606841,   5.13604949,  13.29080635]])

In [77]:
np.random.randint(0, 10, (3,3))

array([[5, 5, 0],
       [1, 5, 9],
       [3, 0, 5]])

In [15]:
# Create identity
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.empty(3)

array([1., 1., 1.])

## The Basics of NumPy Arrays

    1) Attributes of arrays
        Determining the size, shape, memory consumption, and data types of arrays

    2) Indexing of arrays
        Getting and setting the value of individual array elements

    3) Slicing of arrays
        Getting and setting smaller subarrays within a larger array

    4) Reshaping or arrays
        Changing the shape of a given array
        
    5) Joining and splitting of arrays
        Combining multiple arrays into one, and splitting one array into many

## 1. NumPy Array Attributes
    we will define three random arrays, 1D, 2D, and 3D array.
    We will use seed with a set value in order to ensure that the same random arrays are generated each time.

In [17]:
np.random.seed(0) #seed for reproducibility

x1 = np.random.randint(19, size=6) # 1D
x2 = np.random.randint(10, size=(3, 4)) # 2D
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D

In [18]:
print("D's of x3", x3.ndim, "\nShape of x3",
    x3.shape, "\nSize of x3", x3.size, "\nAnd datatype of x3 is", x3.dtype)

D's of x3 3 
Shape of x3 (3, 4, 5) 
Size of x3 60 
And datatype of x3 is int32


In [19]:
x1, x2 ,x3

(array([12, 15,  0,  3,  3,  7]),
 array([[9, 3, 5, 2],
        [4, 7, 6, 8],
        [8, 1, 6, 7]]),
 array([[[7, 8, 1, 5, 9],
         [8, 9, 4, 3, 0],
         [3, 5, 0, 2, 3],
         [8, 1, 3, 3, 3]],
 
        [[7, 0, 1, 9, 9],
         [0, 4, 7, 3, 2],
         [7, 2, 0, 0, 4],
         [5, 5, 6, 8, 4]],
 
        [[1, 4, 9, 8, 1],
         [1, 7, 9, 9, 3],
         [6, 7, 2, 0, 3],
         [5, 9, 4, 4, 6]]]))

## 2. Array Indexing: Accessing Single Elements
    getting the ith value in the array

In [20]:
x1

array([12, 15,  0,  3,  3,  7])

In [21]:
x1[-1]

7

In [22]:
x2

array([[9, 3, 5, 2],
       [4, 7, 6, 8],
       [8, 1, 6, 7]])

In [23]:
x2[0,1]

3

In [24]:
x2[0,3]

2

In [25]:
x2[1][3]

8

## 3. Array Slicing: Accessing Subarrays
    As we can use square brackets [] to access array elements, we can also use them to access subarrays with the slice notation (:)

its syntext is x [start:stop:step]
by defaule is start = 0, stop = size of dimension, step = 1

### 1D subarrays

In [26]:
x = np.arange(90, 100)
x

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
x[:5] # first five elements

array([90, 91, 92, 93, 94])

In [28]:
x[5:] # element after index 5

array([95, 96, 97, 98, 99])

In [29]:
x[4:7] # middle subarray

array([94, 95, 96])

In [30]:
x[::2] # every other element

array([90, 92, 94, 96, 98])

In [31]:
x[::3] # every third element

array([90, 93, 96, 99])

In [32]:
x[1::2] # every other element, starting at index 1 (odd, or 3)

array([91, 93, 95, 97, 99])

When step value is negative, defaults for start and stop are swapped.

In [33]:
x[::-1] # array in reverse

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90])

In [34]:
x[5::-2] #reversed every other form index 5

array([95, 93, 91])

In [35]:
x[9::-2]

array([99, 97, 95, 93, 91])

### Multidimensional subarrays
    it is the same to 1D array, but with multiple slice separated by comas

In [36]:
x2

array([[9, 3, 5, 2],
       [4, 7, 6, 8],
       [8, 1, 6, 7]])

In [37]:
x2[:2, :3] #two rows, three columns

array([[9, 3, 5],
       [4, 7, 6]])

In [38]:
x2[:3, ::2] # all rows, every other columns

array([[9, 5],
       [4, 6],
       [8, 6]])

In [39]:
# subarray dimensions can be reversed together

x2[::-1, ::-1]

array([[7, 6, 1, 8],
       [8, 6, 7, 4],
       [2, 5, 3, 9]])

### Accessing array rows and columns
    if we need to access a single row or columns. You can do this by combining indexing and slicing, using empty slice (:).

In [40]:
x2[:, 0] # first column of martix

array([9, 4, 8])

In [41]:
x2[0, :] # first row of matrix

array([9, 3, 5, 2])

to acces row, To make it easy, the empty slice (:) can be omitted

In [42]:
x2[1]

array([4, 7, 6, 8])

## 5. Respaping of Arrays
    This uses reshape() method commonly.

In [43]:
grid = np.arange(1, 10).reshape(3,3)

grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 6. Array Concatenation and Splitting
    It is also possible to combine multiple arrays into one.

### Concatenation of arrays
To join or concatenate two or many arrays we uses np.concatenate, np.vstack, np.hstack

- np.concatenate

    Note! Concatenate is used only for same size of arrays or matrix.

In [44]:
x = np.array([1,2,3])
y = np.array([9,8,7])

In [45]:
np.concatenate([x, y])

array([1, 2, 3, 9, 8, 7])

In [46]:
np.concatenate([[1,2,3,4,5,6], x, y])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 9, 8, 7])

In [47]:
# using 2D arrays

x2 = np.arange(9).reshape(3,3)

In [48]:
np.concatenate([x2, x2], axis= 1) # concatenate along the second axis (zero indexed)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

To Join mixed dimensions arrays or matrics, it can be done by np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [49]:
x = np.array([1,2,3])

grid = np.arange(6).reshape(2, 3)

grid, x

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([1, 2, 3]))

In [50]:
np.vstack([x, grid]) #vertically stacking the array

array([[1, 2, 3],
       [0, 1, 2],
       [3, 4, 5]])

In [51]:
np.vstack([grid, x])

array([[0, 1, 2],
       [3, 4, 5],
       [1, 2, 3]])

In [52]:
# horizontally stacking the array

y = np.arange(88, 90).reshape(2,1)
y

array([[88],
       [89]])

In [53]:
np.hstack([y, grid]), np.hstack([grid, y])

(array([[88,  0,  1,  2],
        [89,  3,  4,  5]]),
 array([[ 0,  1,  2, 88],
        [ 3,  4,  5, 89]]))

In [54]:
np.dstack([grid, grid]), np.dstack([x3, x3])

(array([[[0, 0],
         [1, 1],
         [2, 2]],
 
        [[3, 3],
         [4, 4],
         [5, 5]]]),
 array([[[7, 8, 1, 5, 9, 7, 8, 1, 5, 9],
         [8, 9, 4, 3, 0, 8, 9, 4, 3, 0],
         [3, 5, 0, 2, 3, 3, 5, 0, 2, 3],
         [8, 1, 3, 3, 3, 8, 1, 3, 3, 3]],
 
        [[7, 0, 1, 9, 9, 7, 0, 1, 9, 9],
         [0, 4, 7, 3, 2, 0, 4, 7, 3, 2],
         [7, 2, 0, 0, 4, 7, 2, 0, 0, 4],
         [5, 5, 6, 8, 4, 5, 5, 6, 8, 4]],
 
        [[1, 4, 9, 8, 1, 1, 4, 9, 8, 1],
         [1, 7, 9, 9, 3, 1, 7, 9, 9, 3],
         [6, 7, 2, 0, 3, 6, 7, 2, 0, 3],
         [5, 9, 4, 4, 6, 5, 9, 4, 4, 6]]]))

### Splitting of arrays

The opposit function of join or concatenate is spliting which use np.split, np.hsplit, and np.vsplit.

In [55]:
x = [1,2,3,66,66,3,2,1]

x1, x2, x3 = np.split(x, [3,5])

x1, x2 ,x3

(array([1, 2, 3]), array([66, 66]), array([3, 2, 1]))

    Note that N spit points lead to N + 1 subarrays.

In [56]:
grid = np.arange(16).reshape((4, 4))

grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
up, low = np.vsplit(grid, [2])

up, low

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [58]:
up, low , n= np.split(grid, [1,3])

up, low, n

(array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]))

In [59]:
left, right = np.hsplit(grid, [2])


left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [60]:
g = np.arange(16).reshape(2,2,4)


g

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
d1, d2 = np.dsplit(g, indices_or_sections= 2)

d1, d2

(array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]),
 array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]]))