## Comparison Operatos as ufuncs

Numpy also implememts comparison operators as uch as < Less then and > greater then as element-wise ufuncs.

> The result of these operators is always an array with a Boolean data type. All six of the standard comparison operations are available:

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

In [2]:
a < 3

array([ True,  True, False, False, False])

In [4]:
a > 3

array([False, False, False,  True,  True])

In [5]:
a >= 3

array([False, False,  True,  True,  True])

In [6]:
a <= 3

array([ True,  True,  True, False, False])

In [7]:
a != 3

array([ True,  True, False,  True,  True])

In [8]:
a == 3

array([False, False,  True, False, False])

In [12]:
(2 * a) == (a ** 2)

array([False,  True, False, False, False])

In [15]:
# in NumPy, these are...

np.less(a, 3), np.greater(a, 3)


(array([ True,  True, False, False, False]),
 array([False, False, False,  True,  True]))

In [23]:
rng = np.random.RandomState(0)

a = rng.randint(20, size=(3, 4))

a

array([[12, 15,  0,  3],
       [ 3,  7,  9, 19],
       [18,  4,  6, 12]])

In [24]:
a < 10

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [False,  True,  True, False]])

In [25]:
np.less(a, 10)

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [False,  True,  True, False]])

![Numpy comparison operators](../../Pictures/Numpy%20Comparison%20operators.png)