## Working with Bollean Arrays

There are a Host of useful operations you can do.

In [1]:
import numpy as np

In [5]:
a = np.random.randint(9, size=(3, 4))

a

array([[2, 5, 4, 1],
       [5, 8, 7, 8],
       [2, 5, 4, 1]])

### Counting entries

To count the number of True entries in a Boolean array, np.count_nonzero is useful:

In [6]:
# how many values are < 4

np.count_nonzero(a< 6)

9

In [7]:
# an other way is

np.sum(a < 6)

9

The benefit of sum() is that like with other NumPy aggregation functions, this summation can be one along rows or columns as well:

In [10]:
# how many values are less then 6 in each row?

np.sum(a < 6, axis=1), np.sum(a < 6, axis=0)

(array([4, 1, 4]), array([3, 2, 2, 2]))

If we're interested in quickly checking whether any or all the values are true, we can use (you guessed it) np.any() or np.all():

In [12]:
# are there any values greater than 3?

np.any(a > 3)

True

In [13]:
np.all(a < 10)

True

In [14]:
np.all(a < 8, axis=1)

array([ True, False,  True])