## Fancy Indexing

In the previous sections, we saw how to access and modify portions of arrays using simple indices (e.g., arr[0]), slices (e.g., arr[:5]), and Boolean masks (e.g., arr[arr > 0]). In this section, we’ll look at another style of array indexing, known as fancy indexing. Fancy indexing is like the simple indexing we’ve already seen, but we pass arrays of indices in place of single scalars. This allows us to very quickly access and modify complicated subsets of an array's values.

### Ecploring Fancy Indexing

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once.

For example, consider the follwoing array:

In [3]:
import numpy as np

rand = np.random.RandomState(42)

x = rand.randint(100, size = 10)

x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [4]:
# Suppose we want to access three different elements. We could do it like this:

[x[3], x[7], x[2]]

[71, 86, 14]

Alternatively, we can pass a single list or array of indices to obtain the same result:

In [5]:
ind = [3, 7, 4]

x[ind]

array([71, 86, 60])

With fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed:

In [6]:
ind = np.array([[3, 7],
                [4, 5]])

x[ind]

array([[71, 86],
       [60, 20]])

Fancy indexing also works in multiple dimensions. Consider the follwoing array:

In [8]:
X = np.arange(12).reshape((3, 4))

X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Like with standard indexing, the fisrt index refers to the row, and the second to the column:

In [9]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])

X[row, col]

array([ 2,  5, 11])

> [0, 2] is the 0 row and 2nd column which is 2

> [1, 1] is the 1st row and the 1st column which is 5

for computation on array: Broadcasting, If we combine a column vector and a row vector within the indices, we get a two-dimensional result:

In [10]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

Here, each row value is matched with each column vector, exactly as we saw in broad‐casting of arithmetic operations. For example:

In [11]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

> It is always important to remember with fancy indexing that the return value reflects the broadcasted shape of the indices, rather than the shape of the array being indexed.