### Mathematical and Statistical Methods

A set of mathematical functions which compute statistics about an entire array or about the data along an axis are accessible as array methods. Aggregations (often called reductions) like sum, mean, and standard deviation std can either be used by calling the array instance method or using the top level NumPy function:

In [1]:
import numpy as np

In [40]:
from numpy import random

arr = random.randn(5,4) # Normally Distributed data

arr = np.array (arr, dtype= np.int64)

arr

array([[ 0,  0,  0, -1],
       [ 1,  0,  0,  0],
       [-1,  0,  0,  0],
       [-1,  1,  0, -1],
       [ 0,  0,  1,  0]], dtype=int64)

In [41]:
arr.mean()

-0.05

> Both of the following methods is use to find mean.

In [42]:
np.mean(arr)

-0.05

In [44]:
arr.sum()

-1

In [45]:
np.sum(arr)

-1

Functions like mean and sum take an optional axis argument which computes the statistic over the given axis, resulting in an array with one fewer dimension:

In [51]:
arr.mean(axis= 1)

array([-0.25,  0.25, -0.25, -0.25,  0.25])

In [53]:
arr.sum(1)

array([-1,  1, -1, -1,  1], dtype=int64)

Other methods like cumsum and cumprod do not aggregate, instead producing an array of the intermediate results:

In [55]:
arr = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [58]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

![Binary Unversal Function](../../Pictures/Basic%20array%20statistical%20methods.png)