## Methods For Bollean Arrays

Boolean values are coerced to 1 (True) and 0 (False) in the above methods. Thus, sum is often used as a means of counting True values in a boolean array:

In [1]:
import numpy as np
from numpy import random

In [21]:
arr = random.randn(100)

arr = np.array(arr, dtype= np.int64)

arr

array([ 0,  0,  0,  0,  0, -1,  1,  1,  1,  2, -1,  0,  0,  0,  0,  0,  0,
        0,  0,  0, -1,  0,  0,  1,  0,  2,  1,  0,  0,  1,  0,  0,  0, -1,
        1,  0,  0,  0, -1,  0,  0,  0,  0,  1,  0,  0,  0,  0, -1,  0,  0,
        0,  1, -1,  0, -1,  1,  0,  0,  0,  1,  0,  0,  0, -1,  0,  0,  2,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1, -1,  0,  2,  0,  0,  0,
        0, -1, -2,  0,  1,  0,  1,  0,  0, -1,  1,  0, -1,  0,  0],
      dtype=int64)

In [27]:
(arr>0).sum() # Number of positive values

20

There are two additional methods, any and all, useful especially for boolean arrays. any tests whether one or more values in an array is True, while all checks if every value is True:

In [28]:
bools = np.array([False, False, True, False])

bools

array([False, False,  True, False])

In [29]:
bools.any()

True

In [30]:
bools.all()

False

These methods also work with non-boolean arrays, where non-zero elements evaluate to True.

In [35]:
arr = np.array((5,5), np.int64)
arr

array([5, 5], dtype=int64)

In [36]:
arr.any()

True

In [37]:
arr.all()

True