## Sorting

Like Python’s built-in list type, NumPy arrays can be sorted in-place using the sort method:

In [1]:
import numpy as np
from numpy import random

In [54]:
arr = random.randn(20)

np.array(arr, dtype=np.float64)

array([-1.13199694, -0.05304625,  0.21395881,  0.01674246,  1.49218603,
       -0.04150519,  0.24443328,  1.3119543 ,  0.09854913, -1.02337609,
       -0.28195458,  1.69227297,  0.84276198,  0.42955094,  0.40510425,
       -1.17803258, -0.62970462,  0.03406009,  2.15553193, -0.45198914])

In [59]:
arr.sort()

arr

array([-1.17803258, -1.13199694, -1.02337609, -0.62970462, -0.45198914,
       -0.28195458, -0.05304625, -0.04150519,  0.01674246,  0.03406009,
        0.09854913,  0.21395881,  0.24443328,  0.40510425,  0.42955094,
        0.84276198,  1.3119543 ,  1.49218603,  1.69227297,  2.15553193])

Multidimensional arrays can have each 1D section of values sorted in-place along an axis by passing the axis number to sort:

In [77]:
arr = random.randn(5,3)

arr = arr *60

In [78]:
arr.sort(1), arr.sort(0)

# Sorted on both axis

arr

array([[-97.10446197, -92.73142859, -76.05020526],
       [-51.1013867 ,   1.0674354 ,  30.92485023],
       [-34.50997598,   6.60537475,  34.70590026],
       [-19.75463375,  30.76029514,  82.1160877 ],
       [-13.45396916,  43.55506604, 178.70938564]])

In [67]:
large_arr = random.randn(10000)

large_arr[:10]

array([-0.68898848,  1.96542293, -2.18155117,  2.32142055, -1.12880548,
        0.58855265, -0.12534573, -0.53181532, -0.4829804 , -0.61853033])

In [69]:
large_arr.sort()

large_arr[:10]

array([-3.83974549, -3.7193878 , -3.69472119, -3.42341941, -3.3528653 ,
       -3.22341458, -3.16946589, -3.1543115 , -3.14735427, -3.06743991])

In [70]:
large_arr[int(.5 *len(large_arr))] # 5% quantile

-0.0169936412435058