### Creating ndarrays

In [1]:
import numpy as np

data = [6, 7.5, 8, 0, 1]

In [2]:
arr1 = np.array(data)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

##### Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array

In [3]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [4]:
# Converting into np array
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# Dimenations of an array

arr2.ndim

2

In [6]:
# Shape of an np array

arr2.shape

(2, 4)

In [7]:
# Data Type of arrays

arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [8]:
# Creating 1D array of zeros of 10 digits

np.zeros(10, float, "F")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# Creating M-D array of Zeros

np.zeros((4, 3), int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
# Creating an empty array by numpy
# An empty array changes values by it self

np.empty((3, 3, 2), np.int16)

array([[[ 92,  63],
        [ 63,  92],
        [ 67,  58]],

       [[ 92,  85],
        [115, 101],
        [114, 115]],

       [[ 92, 109],
        [ 98, 107],
        [109, 117]]], dtype=int16)

> Arange is an array-valued version of the built-in Python range function:

In [11]:
np.arange(1, 51, 2.25, np.float16)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  , 12.25, 14.5 , 16.75, 19.  ,
       21.25, 23.5 , 25.75, 28.  , 30.25, 32.5 , 34.75, 37.  , 39.25,
       41.5 , 43.75, 46.  , 48.25, 50.5 ], dtype=float16)

In [12]:
np.eye(4, 4, 0, int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Data Types for ndarrays

In [13]:
arr01 = np.array([1,2,3], dtype= np. float64)

arr01.dtype

dtype('float64')

In [14]:
arr02 = np.int32

arr02

numpy.int32

In [15]:
# Changing 1 type of array to other

a = ([ 3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

a = np.array(a)

a.dtype

dtype('float64')

In [16]:
# As the array 'a' is of data type float
# then, converting to int

inted_array = a.astype(np.int8)

inted_array

array([ 3, -1, -2,  0, 12, 10], dtype=int8)

In [17]:
# Let's convert back to float

float_array = inted_array.astype(np.float32)

float_array

array([ 3., -1., -2.,  0., 12., 10.], dtype=float32)

In [18]:
# Can also change string array

b =np.array (['1.25', '-9.6', '4.2'], np.string_)



b = b.astype(np.float16)

b,print(b)

[ 1.25 -9.6   4.2 ]


(array([ 1.25, -9.6 ,  4.2 ], dtype=float16), None)

# > Note that we can't perform operations (+-*/) on lists, then we should convert it to np.array.

In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [20]:
arr = arr.astype(int)

In [21]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [22]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [24]:
arr *0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

### Basic Indexing and Slicing

##### NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [25]:
array = np.arange(10)

array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Accessing a specfic index

array[1]

1

In [27]:
# Accessing a specfic range of indexes of an array

array[0:6]

array([0, 1, 2, 3, 4, 5])

In [28]:
# Changing a specfic range of an array .e.g

array[7:9] = [12,13]


array

array([ 0,  1,  2,  3,  4,  5,  6, 12, 13,  9])

##### An important first distinction from lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [29]:
arr_slice = array[5:7]

arr_slice[1] = 15

arr_slice , array

(array([ 5, 15]), array([ 0,  1,  2,  3,  4,  5, 15, 12, 13,  9]))

##### See, had a slice of the main array (array) and pic its two values 5 and 6,
##### And then, change the value of the slice 1st value and display in the main array
#### To copy values use ***copy()*** function with (.)

> With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:


In [30]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2d[2]

array([7, 8, 9])

In [32]:
# to access individual element, can pass comma separated list of separate the list e.g.

arr2d[0,2]

3

In [33]:
arr2d[0][2]

3

![2D Array](../../Pictures/2darray.png)

In [34]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

##### In multidimensional arrays, if you omit later indices, the returned object will be a lowerdimensional ndarray consisting of all the data along the higher dimensions. So in the 2 × 2 × 3 array arr3d

In [35]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [37]:
old_values = arr3d[0].copy()

In [38]:
arr3d[0] = [[0,1,0],[1,1,0]]

In [39]:
arr3d

array([[[ 0,  1,  0],
        [ 1,  1,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0] = old_values

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0,0], arr3d[0,1], arr3d[1,0], arr3d[1,1]

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]))

### Indexing with slices

In [42]:
arr2d[:2], # All 2

(array([[1, 2, 3],
        [4, 5, 6]]),)

In [43]:
arr2d[:2, :1]

array([[1],
       [4]])

In [44]:
arr2d[1, :2]

array([4, 5])

In [45]:
arr2d[2, :1]

array([7])

In [46]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

### Boolean Indexing

In [58]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [54]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [53]:
from numpy import random

data = random.randn(7,4)

data

array([[ 2.31724494, -0.1548227 ,  1.28191842,  0.08206875],
       [-0.85541779, -0.09463435,  1.43593353,  0.89031928],
       [-1.98810486, -0.34936983, -0.90035615,  0.21418163],
       [-0.77836889, -0.39931307, -0.89411755, -0.24797145],
       [-0.58746149, -0.86440765, -0.4710335 ,  0.16700276],
       [ 1.06006885,  0.40520943,  0.55902118, -0.47018509],
       [-0.39638659,  0.3118922 ,  1.66260986,  1.11220916]])

![2D Array scalling](../../Pictures/2darrayscalling.png)

### Fancy Indexing
> Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.


In [66]:
# suppose we had a 8 x 4 array:

arr = np.empty((8,4), np.int16)

arr

array([[ 92,  63,  63,  92],
       [ 67,  58,  92,  85],
       [115, 101, 114, 115],
       [ 92, 109,  98, 107],
       [109, 117,  92,  65],
       [112, 112,  68,  97],
       [116,  97,   0,   0],
       [  0,   0,   0,  10]], dtype=int16)

In [67]:
for i in range(8):
    arr[i] = i

arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]], dtype=int16)

##### To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order:

In [72]:
arr[[4,3,1,6, 2]]

array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [1, 1, 1, 1],
       [6, 6, 6, 6],
       [2, 2, 2, 2]], dtype=int16)

##### Hopefully this code did what you expected! Using negative indices select rows from the end

In [77]:
arr[[-3, -2, -5, -4]]

array([[5, 5, 5, 5],
       [6, 6, 6, 6],
       [3, 3, 3, 3],
       [4, 4, 4, 4]], dtype=int16)

Passing multiple index arrays does something slightly different; it selects a 1D array of  elements corresponding to each tuple of indices:


In [89]:
arr = np.arange(40).reshape(8,5)

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [92]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 5, 28, 36, 12])

Take a moment to understand what just happened: the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected. The behavior of fancy indexing in this case is a bit different from what some users might have expected (myself included), which is the rectangular region formed by selecting a subset of the matrix’s rows and columns.

> Here is one way to get that:

In [95]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 5,  8,  6,  7],
       [25, 28, 26, 27],
       [35, 38, 36, 37],
       [10, 13, 11, 12]])

### Transposing Arrays and Swapping Axes

In [105]:
arr = np.arange(15).reshape((3,5))

arr,        arr.T

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]))

In [128]:
arr = random.randn(6, 3)

arr.astype(np.int16),       np.dot(arr.T, arr)

(array([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, -1],
        [ 0, -1,  1],
        [ 0,  1,  0]], dtype=int16),
 array([[ 1.03137353, -0.8262663 , -1.08926866],
        [-0.8262663 ,  3.47008538, -1.83282469],
        [-1.08926866, -1.83282469,  5.1504872 ]]))

> For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute the axes (for extra mind bending):

In [129]:
arr = np.arange(16).reshape((2, 2, 4))

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [134]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [135]:
# Swapping the axes

arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])