# Unique Other Set Logic

NumPy has some basic set operations for one-dimensional ndarrays. Probably the most commonly used one is np.unique, which returns the sorted unique values in an array:

In [1]:
import numpy as np

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [4]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [6]:
ints = np.array([1,2,1,1,2,2,3,3,1,2,4,5,6,5,6])

In [8]:
np.unique(ints)

array([1, 2, 3, 4, 5, 6])

Another function, np.in1d, tests membership of the values in one array in another, returning a boolean array:

In [9]:
values = np.array([1,2,3,4,1,0,0,1,4,5,2,7,1,9,8,8,9,7,2,3,1,6,5,4])

In [12]:
np.in1d(values, [1,10,15,90,5,6,7,8])

array([ True, False, False, False,  True, False, False,  True, False,
        True, False,  True,  True, False,  True,  True, False,  True,
       False, False,  True,  True,  True, False])

#### Some other Functions

In [19]:
x = np.array([1,2,3,4,5,6,1,5,3,1,0,2])

y = np.array([2,6,3,0,6,3,6,11,9,0,1,2,1])

np.intersect1d(x, y), np.intersect1d(y, x)

(array([0, 1, 2, 3, 6]), array([0, 1, 2, 3, 6]))

In [14]:
np.union1d(x,y)

array([ 0,  1,  2,  3,  4,  5,  6,  9, 11])

In [16]:
np.setdiff1d(x,y), np.setdiff1d(y,x)

(array([4, 5]), array([ 9, 11]))

In [18]:
np.setxor1d(x,y), np.setxor1d(y,x)

(array([ 4,  5,  9, 11]), array([ 4,  5,  9, 11]))

![Array Set Operations](../../Pictures/Array%20Set%20Operations.png)