## Storing Arrays on disk in Binary Format

np.save and np.load are the two workhorse functions for efficiently saving and loading array data on disk. Arrays are saved by default in an uncompressed raw binary format with file extension .npy.

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('../../CSV Files/temp_some_arr', arr)

If the file path does not already end in .npy, the extension will be appended. The array on disk can then be loaded using np.load:

In [6]:
np.load('../../CSV Files/temp_some_arr.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You save multiple arrays in a zip archive using np.savez and passing the arrays as keyword arguments:

In [7]:
np.savez('../../CSV Files/temp_arr', a= arr, b= arr)

When loading an .npz file, you get back a dict-like object which loads the individual arrays lazily:

In [8]:
ach = np.load('../../CSV Files/temp_arr.npz')

In [9]:
ach['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ach['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])